- build.gradle
> Feature 14 sonar

- build.gradle
- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionDeviceDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionDevice.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/auth/TestBuilderAuthentication.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionDeviceTestBuilderResource.kt
> Feature 16 devices

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceModelTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceController.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceModelController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionDeviceDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionDeviceModelDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionDeviceModel.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceModelTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/VisitorSessionTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/auth/TestBuilderAuthentication.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionDeviceModelTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionDeviceTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/VisitorSessionTestBuilderResource.kt
> Added support for device models

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionPageLayoutTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/pages/ExhibitionPageLayoutController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionPageLayoutDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionPageLayout.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageLayoutTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/auth/TestBuilderAuthentication.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionPageLayoutTestBuilderResource.kt
> Added support for page layouts

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionPageTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/pages/ExhibitionPageController.kt
- src/main/kotlin/fi/metatavu/muisti/pages/ExhibitionPageLayoutController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionPageDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionPage.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageLayoutTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/AbstractFunctionalTest.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/auth/TestBuilderAuthentication.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ApiTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionPageLayoutTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionPageTestBuilderResource.kt
> Feature 24 pages

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionPageTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/pages/ExhibitionPageController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionPageDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionPage.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionPageTestBuilderResource.kt
> Review comments

- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
> Renamed event type to event action

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/PageLayoutsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/PageLayoutTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceController.kt
- src/main/kotlin/fi/metatavu/muisti/pages/PageLayoutController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionDeviceDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/PageLayoutDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionDevice.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/PageLayout.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/PageLayoutTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionDeviceTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/PageLayoutTestBuilderResource.kt
> API support for screen orientation

- build.gradle
- docker-compose.yml
- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/AbstractTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceGroupTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceModelTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionPageTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionRoomTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/PageLayoutTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/VisitorSessionTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/realtime/RealtimeNotificationController.kt
- src/main/kotlin/fi/metatavu/muisti/realtime/mqtt/MqttConnection.kt
- src/main/kotlin/fi/metatavu/muisti/realtime/mqtt/MqttController.kt
- src/main/kotlin/fi/metatavu/muisti/realtime/mqtt/MqttException.kt
- src/main/kotlin/fi/metatavu/muisti/realtime/mqtt/MqttMessage.kt
- src/main/kotlin/fi/metatavu/muisti/settings/MqttSettings.kt
- src/main/kotlin/fi/metatavu/muisti/settings/SettingsController.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/TestBuilder.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/mqtt/TestMqttClient.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/mqtt/TestMqttSubscription.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/settings/TestSettings.kt
> Feature 38 pages mqtt

- src/main/resources/fi/metatavu/muisti/changelog.xml
> Fixed issue with migrations

- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionDevice.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/PageLayout.kt
> Fixed issue with missing Enumerated annotations

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/realtime/RealtimeNotificationController.kt
- src/main/kotlin/fi/metatavu/muisti/sessions/VisitorSessionController.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/VisitorSessionTestsIT.kt
> Initial version of visitor session realtime notifications

- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
> Added support for using externalKeyCode as an event trigger

- src/main/resources/fi/metatavu/muisti/changelog.xml
> Fixed issue with migration

- src/main/kotlin/fi/metatavu/muisti/api/DeviceModelsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceModelTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/devices/DeviceModelController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/DeviceModelDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/DeviceModel.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/DeviceModelTestsIT.kt
> Added support for physical device screen size and device depth

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/PageLayoutsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionContentVersionTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionPageTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/contents/ExhibitionPageController.kt
- src/main/kotlin/fi/metatavu/muisti/contents/PageLayoutController.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/ExhibitionContentVersionController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionContentVersionDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionPageDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionContentVersion.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionContentVersionTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/auth/TestBuilderAuthentication.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionContentVersionTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionPageTestBuilderResource.kt
> Feature 57 exhibition content versions

- build.gradle
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/FileTestsIT.kt
> Feature 59 windows compatibility

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceGroupTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionFloorTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionRoomTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceGroupController.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/ExhibitionFloorController.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/ExhibitionRoomController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionDeviceGroupDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionFloorDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionRoomDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionDeviceGroup.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionFloor.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceGroupTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionFloorTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionRoomTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/auth/TestBuilderAuthentication.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionDeviceGroupTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionFloorTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionRoomTestBuilderResource.kt
> Feature 60 floors

- src/main/resources/fi/metatavu/muisti/changelog.xml
> Fixed migrations

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionDeviceDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionDevice.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/AbstractFunctionalTest.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionContentVersionTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionDeviceGroupTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionDeviceTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionFloorTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionPageTestBuilderResource.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/builder/impl/ExhibitionRoomTestBuilderResource.kt
> Feature 63 device index page

- README.md
- build.gradle
- src/main/kotlin/fi/metatavu/muisti/realtime/mqtt/MqttController.kt
> Fixing sonar

- build.gradle
> Fixed sonar issues

- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
> Added support for group events

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionFloorTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/ExhibitionFloorController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionFloorDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionFloor.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionFloorTestsIT.kt
> Feature 89 floor plan support

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionRoomTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/ExhibitionRoomController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionRoomDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionRoom.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionRoomTestsIT.kt
> Added support for room polygons

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionPageTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/contents/ExhibitionPageController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionPageDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionPage.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
> Added support for specifying page transitions

- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionFloorTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionRoomTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/ExhibitionFloorController.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/ExhibitionRoomController.kt
- src/main/kotlin/fi/metatavu/muisti/geometry/GeometryTransformer.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionRoomDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionRoom.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionRoomTestsIT.kt
Resolves #97 
Changed geoShape persistence model to user geometry data type
Added needed DB migrations
Added common geometry package
Fixed tests
> Fixed GeoJSON polygon format

- src/main/kotlin/fi/metatavu/muisti/geometry/GeometryTransformer.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionRoomTestsIT.kt
> Fixed GeoJSON format

- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionPageTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/contents/ExhibitionPageController.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
> Fixed transition format

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/RfidAntennaTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/devices/RfidAntennaController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/RfidAntennaDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/RfidAntenna.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/RfidAntennaTestsIT.kt
> Added CRUD support for RFID antennas

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/realtime/RealtimeNotificationController.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceGroupTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/RfidAntennaTestsIT.kt
> Feature 116 device group mqtt messages

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionRoomTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/ExhibitionRoomController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionRoomDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionRoom.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionRoomTestsIT.kt
> Added support for defining room's color

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceTestsIT.kt
> Fixed issue #127

- src/main/kotlin/fi/metatavu/muisti/files/FileController.kt
- src/main/kotlin/fi/metatavu/muisti/files/storage/S3FileStorageProvider.kt
- src/main/kotlin/fi/metatavu/muisti/media/ImageReader.kt
- src/main/kotlin/fi/metatavu/muisti/media/ImageScaler.kt
- src/main/kotlin/fi/metatavu/muisti/media/ImageWriter.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/FileTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/PageLayoutTestsIT.kt
> Added support for stored file thumbnails

- src/main/kotlin/fi/metatavu/muisti/api/DeviceModelsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/contents/PageLayoutController.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/DeviceModelTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceGroupTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionRoomTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/PageLayoutTestsIT.kt
> Improved delete foreign key constraint handling

- src/main/kotlin/fi/metatavu/muisti/api/DeviceModelsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceModelTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/devices/DeviceModelController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/DeviceModelDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/DeviceModel.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/DeviceModelTestsIT.kt
> Added support for device orientation

- src/main/kotlin/fi/metatavu/muisti/api/SubLayoutsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/SubLayoutTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/contents/SubLayoutController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/SubLayoutDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/SubLayout.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/FileTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/SubLayoutTestsIT.kt
> Feature 140 support for sublayouts

- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
> Added support for scripted resources

- src/main/kotlin/fi/metatavu/muisti/visitors/VisitorSessionController.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/VisitorSessionTestsIT.kt
> Hotfix 146 visitor session variable update

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/contents/ExhibitionPageController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionPageDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionPage.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/FileTestsIT.kt
> Added support for changing device page order

- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
> Feature 149 event trigger id and name

- README.md
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/FileTestsIT.kt
> Bumped spec

- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
> Added tests for deleted page page order

- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
> Added support for resource mode

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionPageTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/contents/ExhibitionPageController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionPageDAO.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
> Remove page order from device

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionDeviceDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionDevice.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
> Removed device index page

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/VisitorSessionTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/VisitorSessionDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/VisitorSession.kt
- src/main/kotlin/fi/metatavu/muisti/visitors/VisitorSessionController.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/VisitorSessionTestsIT.kt
> Added support for specifying visitor session language

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceGroupTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceGroupController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionDeviceGroupDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionDeviceGroup.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceGroupTestsIT.kt
> Feature 180 visitor session start strategy

- src/main/resources/fi/metatavu/muisti/changelog.xml
> Fixed broken migration

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/VisitorTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/keycloak/KeycloakController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/VisitorDAO.kt
- src/main/kotlin/fi/metatavu/muisti/visitors/VisitorController.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/VisitorSessionTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/VisitorTestsIT.kt
> Added support for extra user info

- README.md
- docker-compose.yml
- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/VisitorSessionDAO.kt
- src/main/kotlin/fi/metatavu/muisti/settings/SettingsController.kt
- src/main/kotlin/fi/metatavu/muisti/visitors/VisitorSessionController.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/VisitorSessionTestsIT.kt
> Added support for visitor session timeout

- src/main/kotlin/fi/metatavu/muisti/api/AbstractApi.kt
- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/VisitorVariableTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/VisitorVariableDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/VisitorVariable.kt
- src/main/kotlin/fi/metatavu/muisti/visitors/VisitorSessionController.kt
- src/main/kotlin/fi/metatavu/muisti/visitors/VisitorVariableController.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/VisitorSessionTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/VisitorVariableTestsIT.kt
> Added support for visitor variable CRUD operations

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionDeviceDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionDevice.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceTestsIT.kt
> Added support for specifying idle page for devices

- scripts/cleanBuildAll.sh
> Added VisitorsView widget type

- docker-compose.yml
- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionPageTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/contents/ExhibitionPageController.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceController.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceGroupController.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/ContentVersionController.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/GroupContentVersionController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionDeviceDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionPageDAO.kt
- src/main/kotlin/fi/metatavu/muisti/utils/CopyException.kt
- src/main/kotlin/fi/metatavu/muisti/utils/IdMapper.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/AbstractFunctionalTest.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceGroupTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
> Feature 206 copy device group

- docker-resources/keycloak.cli
- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/contents/ExhibitionPageController.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceController.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceGroupController.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/ContentVersionController.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/GroupContentVersionController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ContentVersionDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionDeviceGroupDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ContentVersion.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/AbstractFunctionalTest.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceGroupTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/GroupContentVersionTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/RfidAntennaTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/VisitorSessionTestsIT.kt
> Hotfix 208 copy issues

- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceGroupController.kt
- src/main/kotlin/fi/metatavu/muisti/devices/RfidAntennaController.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceGroupTestsIT.kt
> Feature 209 copy antennas

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ContentVersionTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/contents/ContentVersionController.kt
- src/main/kotlin/fi/metatavu/muisti/contents/GroupContentVersionController.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceGroupController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ContentVersionDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ContentVersion.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ContentVersionTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceGroupTestsIT.kt
> Added support for specifying content version active condition

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/PageLayoutsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/contents/ExhibitionPageController.kt
- src/main/kotlin/fi/metatavu/muisti/contents/PageLayoutController.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceController.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceGroupController.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/ExhibitionController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionDeviceDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionPageDAO.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceGroupTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
Modified PageLayout delete functionalities
Resolves: #218
> Added additional filters for PageLayout and ExhibitionDevice

- src/main/kotlin/fi/metatavu/muisti/api/ExhibitionsApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionDeviceDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionDevice.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceGroupTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceTestsIT.kt
> Added image load strategy to device

- src/main/kotlin/fi/metatavu/muisti/keycloak/KeycloakAccessToken.kt
- src/main/kotlin/fi/metatavu/muisti/keycloak/KeycloakController.kt
> Fixed issue #227

- src/main/kotlin/fi/metatavu/muisti/keycloak/KeycloakController.kt
- src/main/kotlin/fi/metatavu/muisti/keycloak/KeycloakControllerToken.kt
> Changed keycloak controller access token logic

- README.md
- src/main/kotlin/fi/metatavu/muisti/api/V1ApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/api/translate/ExhibitionDeviceGroupTranslator.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceGroupController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionDeviceGroupDAO.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/model/ExhibitionDeviceGroup.kt
- src/main/resources/fi/metatavu/muisti/changelog.xml
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceGroupTestsIT.kt
> Feature 243 index page timeout

- api-client/build.gradle
- api-spec/build.gradle
- build.gradle
- src/main/kotlin/fi/metatavu/muisti/api/V1ApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/contents/ContentVersionController.kt
- src/main/kotlin/fi/metatavu/muisti/contents/ExhibitionPageController.kt
- src/main/kotlin/fi/metatavu/muisti/contents/GroupContentVersionController.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceController.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceGroupController.kt
- src/main/kotlin/fi/metatavu/muisti/devices/RfidAntennaController.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/ExhibitionController.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/ExhibitionFloorController.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/ExhibitionRoomController.kt
- src/main/kotlin/fi/metatavu/muisti/files/FileController.kt
- src/main/kotlin/fi/metatavu/muisti/persistence/dao/ExhibitionDAO.kt
- src/main/kotlin/fi/metatavu/muisti/visitors/VisitorVariableController.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/AbstractFunctionalTest.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ContentVersionTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/DeviceModelTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionDeviceGroupTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionFloorTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionPageTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionRoomTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/ExhibitionTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/GroupContentVersionTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/PageLayoutTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/VisitorSessionTestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/VisitorSessionV2TestsIT.kt
- src/test/kotlin/fi/metatavu/muisti/api/test/functional/VisitorVariableTestsIT.kt
> Feature 246 exhibition copy

- src/main/kotlin/fi/metatavu/muisti/api/V1ApiImpl.kt
- src/main/kotlin/fi/metatavu/muisti/devices/ExhibitionDeviceGroupController.kt
- src/main/kotlin/fi/metatavu/muisti/exhibitions/ExhibitionController.kt
> Fixed issue #249

- src/main/resources/db/changeLog.xml
https://github.com/Metatavu/muisti-api/issues/257
> changeset to update invalid enum
